frase = "   CurSo Em VidEo     "
print(frase)
print(frase[:6])
print(frase[6:])
print(frase[::2])
print(frase.istitle())
print(frase.title())
print((frase.split()))
print(frase.strip())
print("-$-".join(frase.strip().split()))
print(frase.upper())
print((frase.lower()))
print(frase.strip().capitalize())
print(frase.count("o"))
print(frase.replace("CurSo", "Igor").strip())
print("CurSo" in frase)
print(frase.find("CurSo"))